[[rules]]
query = "pos ->link_pos ctok_part"
target = 2
ns = "PART_CLEAN"
name = "pos"
value = { copy = 1 }

[[rules]]
query = "pos ->link_pos ctok_part"
target = 2
ns = "PART_CLEAN"
name = "auto_pos"
value = { copy = 1 }

[[rules]]
query = "lemma ->link_lemma ctok_part"
target = 2
ns = "PART_CLEAN"
name = "lemma"
value = { copy = 1 }

[[rules]]
query = "lemma ->link_lemma ctok_part"
target = 2
ns = "PART_CLEAN"
name = "auto_lemma"
value = { copy = 1 }
