[[rules]]
query = "pos ->link_pos ctok_part"
target = [2]
anno = "PART_CLEAN::pos"
value = { copy = 1 }

[[rules]]
query = "pos ->link_pos ctok_part"
target = [2]
anno = "PART_CLEAN::auto_pos"
value = { copy = 1 }

[[rules]]
query = "lemma ->link_lemma ctok_part"
target = [2]
anno = "PART_CLEAN::lemma"
value = { copy = 1 }

[[rules]]
query = "lemma ->link_lemma ctok_part"
target = [2]
anno = "PART_CLEAN::auto_lemma"
value = { copy = 1 }
