[[import]]
format = "exmaralda"
path = "./data/4/"
config = {}

[[graph_op]]
action = "revise"

[graph_op.config.node_names]
"4" = "SeiKo-Preview"

[[graph_op]]
action = "map"

[graph_op.config]
rule_file = "rename_rules.toml"

[[export]]
format = "graphml"
path = "./data/5_annis/"

[export.config]
guess_vis = true
zip = true
