[[rules]]
query = "annis:node_name=/meta..+/ _ident_ annis:node_type=/corpus/"
target = 1
anno = "src::id"
value = {target = 1, replacements = [["meta/", ""]]}

[[rules]]
query = "annis:node_name=/SeiKo..+/ _ident_ annis:node_type=/corpus/"
target = 1
anno = "tgt::id"
value = {target = 1, replacements = [["SeiKo/", ""]]}
